name: depend-test

channels:
  - conda-forge
  - conda

dependencies:
  - pandas=1.4.2
  - pip=20
  - python=3.8.13
  - black=22.3.0
  - pytest=7.1.2
  - openpyxl=3.0.9
  - pylint=2.12.2
  - coverage=6.4
  - conda-pack=0.7.0
  - snowflake-connector-python=2.7.7
  - boto3=1.24.49