service: test

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1

functions:
  hello:
    handler: main.print_hi
    role: arn:aws:iam::798104083011:role/test-lambda-role
